"""Add sanitized CDP failure detail to the Chromium OAuth stage-one probe.

This wrapper intentionally changes no request parameter or header. It reuses the
existing stage-one-only Chromium OAuth probe and observes only CDP network events
already generated by that request. It emits normalized ``net::ERR_*`` failure
codes and header names, never header values, request IDs, query values, OAuth
credentials, response bodies, cookies, signed URLs, or audio bytes.
"""

from __future__ import annotations

import json
import re
import sys
from typing import Any
from urllib.parse import urlsplit

import yandex_upload_cdp_oauth_probe as base


_FORMAT = "musicark-yandex-upload-cdp-failure-detail-probe-v1"
_NET_ERROR_RE = re.compile(r"^net::ERR_[A-Z0-9_]{1,120}$")


def _safe_net_error(value: Any) -> str | None:
    clean = str(value or "").strip().upper()
    if not clean:
        return None
    return clean if _NET_ERROR_RE.fullmatch(clean) else "unknown"


def _header_names(headers: Any) -> list[str]:
    if not isinstance(headers, dict):
        return []
    names = {str(name or "").strip().lower() for name in headers.keys()}
    return sorted(name for name in names if name)


def _same_stage1_url(value: Any, expected_origin: str) -> bool:
    try:
        actual = urlsplit(str(value or ""))
        expected = urlsplit(expected_origin)
    except ValueError:
        return False
    return bool(
        actual.scheme == expected.scheme
        and actual.hostname == expected.hostname
        and (actual.path or "/") == "/loader/upload-url"
    )


class _FailureCapture:
    def __init__(self, expected_origin: str) -> None:
        self.expected_origin = expected_origin
        self.request_methods: dict[str, str] = {}
        self.post_header_names: list[str] = []
        self.preflight_header_names: list[str] = []
        self.post_failure_code: str | None = None
        self.preflight_failure_code: str | None = None

    def observe(self, message: Any) -> None:
        if not isinstance(message, dict):
            return
        method = str(message.get("method") or "")
        params = message.get("params") if isinstance(message.get("params"), dict) else {}
        request_id = str(params.get("requestId") or "")

        if method == "Network.requestWillBeSent":
            request = params.get("request") if isinstance(params.get("request"), dict) else {}
            if not _same_stage1_url(request.get("url"), self.expected_origin):
                return
            request_method = str(request.get("method") or "").upper()
            if request_id:
                self.request_methods[request_id] = request_method
            names = _header_names(request.get("headers"))
            if request_method == "POST":
                self.post_header_names = names
            elif request_method == "OPTIONS":
                self.preflight_header_names = names
            return

        if method != "Network.loadingFailed" or request_id not in self.request_methods:
            return
        code = _safe_net_error(params.get("errorText"))
        request_method = self.request_methods.get(request_id)
        if request_method == "POST":
            self.post_failure_code = code
        elif request_method == "OPTIONS":
            self.preflight_failure_code = code

    def payload(self) -> dict[str, Any]:
        return {
            "postFailureCode": self.post_failure_code,
            "preflightFailureCode": self.preflight_failure_code,
            "postHeaderNames": self.post_header_names,
            "preflightHeaderNames": self.preflight_header_names,
        }


def run(args: Any) -> tuple[dict[str, Any], int]:
    expected_origin = str(args.stage1_base_url or "").rstrip("/")
    original_client = base.cdp.CdpClient
    holder: dict[str, _FailureCapture] = {}

    class _CapturingCdpClient(original_client):
        def __init__(self, websocket_url: str) -> None:
            super().__init__(websocket_url)
            capture = _FailureCapture(expected_origin)
            holder["capture"] = capture
            self._failure_capture = capture

        def recv_event(self, *, timeout: float = 0.5):  # noqa: ANN201
            message = super().recv_event(timeout=timeout)
            self._failure_capture.observe(message)
            return message

    base.cdp.CdpClient = _CapturingCdpClient
    try:
        payload, code = base.run(args)
    finally:
        base.cdp.CdpClient = original_client

    capture = holder.get("capture") or _FailureCapture(expected_origin)
    payload["format"] = _FORMAT
    stage1 = payload.get("stage1") if isinstance(payload.get("stage1"), dict) else {}
    stage1["cdpFailureDetail"] = capture.payload()
    payload["stage1"] = stage1
    safety = payload.get("safety") if isinstance(payload.get("safety"), dict) else {}
    safety.update(
        {
            "cdp_error_text_values_included": False,
            "cdp_normalized_net_error_codes_only": True,
            "cdp_header_values_included": False,
        }
    )
    payload["safety"] = safety
    return payload, code


def main() -> int:
    parser = base.build_parser()
    args = parser.parse_args()
    if args.launch_wait < 0 or args.launch_wait > 60:
        raise SystemExit("--launch-wait must be between 0 and 60 seconds")
    if args.timeout <= 0 or args.timeout > 120:
        raise SystemExit("--timeout must be between 0 and 120 seconds")
    try:
        payload, code = run(args)
    except Exception as exc:  # noqa: BLE001 - safe CLI boundary.
        print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False))
        return 2
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return code


if __name__ == "__main__":
    sys.exit(main())
