name: musicark_ui
description: "MusicArk Yandex, local library, identity matching, and variant verification desktop app."
publish_to: 'none'

version: 0.5.1+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
